const swaggerAutogen = require("swagger-autogen")({
  openapi: "3.0.0"
});

// const DescriptionSchema = require("./src/models/DescriptionSchema")
// const AdminSchema = require("./src/models/AdminSchema")
// console.log(DescriptionSchema.swaggerSchema)
// console.log(AdminSchema.swaggerSchema)
// const swaggerSchemas = {
//   descriptions: DescriptionSchema.swaggerSchema,
//   admins: AdminSchema.swaggerSchema,
// }

const fs = require("fs");
const path = require("path");
const modelsPath = path.resolve(__dirname);
const m2s = require("mongoose-to-swagger");

let swaggerSchemas = {};
console.log(modelsPath);
const filesPath = fs.readdirSync(modelsPath + "/models");

filesPath.map((file) => {
  //   require(modelsPath + '/' + file);
  // console.log(modelsPath + '/' + file)
  console.log(file.replace(".js", "").split(".")[0]);

  swaggerSchemas[file.replace(".js", "").split(".")[0]] = m2s(require(`./models/${file}`), {
    props: ["ref", "refAllOf", "default"], //whitelist fields
    omitFields: ["_id"] //omitfields
  });
});
// console.log("swaggerSchemas:-", swaggerSchemas)

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:4000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    // {
    //   name: "User",
    //   description: "Endpoints",
    // },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description..."
    }
  },
  definitions: {
    // 1stWay
    // components: {
    //   schemas: swaggerSchemas
    // },
    // ...swaggerSchemas,
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe"
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents"
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company"
          }
        }
      ]
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: ""
    },
    Description: {
      $name: "Description",
      $age: 09,
      about: "123"
    }
  },
  definitions: {
    ...swaggerSchemas
  }
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./bin/www"); // Your project's root file
});
